rules:
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - extends
    - tailwind
    - layer
    - variants
  no-descending-specificity:
  order/order:
  - custom-properties
  - at-rules
  - declarations
  - rules
  order/properties-order:
  - content
  - properties:
    - position
    - top
    - right
    - bottom
    - left
    - z-index
    - order
    - float
  - properties:
    - flex
    - flex-basis
    - flex-grow
    - flex-shrink
    - display
    - opacity
    - visibility
    - overflow
  - properties:
    - transform
    - transition
    - animation
  - properties:
    - flex-direction
    - flex-wrap
    - flex-flow
    - justify-content
    - align-items
    - align-content
    - order
    - align-self
  - properties:
    - box-sizing
    - width
    - min-width
    - max-width
    - height
    - min-height
    - max-height
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-radius
    - box-shadow
  - properties:
    - background
    - background-color
    - cursor
  - properties:
    - font-family
    - font-size
    - font-weight
    - font-style
    - text-align
    - text-transform
    - line-height
    - word-spacing
    - color
